#!/bin/bash
#
# qb
#
# script that uses chewie to implement a bash-specific chat bot.
#

if [ "$CHEWIE_API" == "ollama" ]; then
QB_MODEL="codellama:7b-instruct"
elif [ "$CHEWIE_API" == "openai" ]; then
QB_MODEL="gpt-3.5-turbo"
else
QB_MODEL="codellama:7b-instruct"
CHEWIE_API="ollama"
fi

QB_CONTEXT_PATH=~/.cache/chewie
QB_CONTEXT=$QB_CONTEXT_PATH/qb-context.json

if [ "$1" == "-h" ] ; then
    echo "Usage: qb [options]"
    echo "Options:"
    echo "  -h  Display this help message."
    echo "  -s  Setup (or reset) qb."
    exit 0
fi

if [ "$1" == "-s" ] ; then
    echo "Setting up chewie... "
    echo "Using API \"$CHEWIE_API\""
    echo "Using model \"$QB_MODEL\""
    echo "Using context file \"$QB_CONTEXT\""
    mkdir -p $QB_CONTEXT_PATH
    chewie r u ctx="$QB_CONTEXT" mdl="$QB_MODEL" sys="You are an intelligent assistant helping me use bash on Linux. All of your responses should be in the context of using bash on Linux. If you do not know the answer to a question, just say \"I don\'t know\"." > /dev/null
    echo "done!"
    exit 0
fi

printf "%q" "$@" | chewie -c "$QB_CONTEXT" -m "$QB_MODEL"
