/**
 * setting.h
 * 
 * Settings that are generated by actions.
 */
#ifndef _SETTING_H
#define _SETTING_H

/// Strings used as setting object keys
#define SETTING_KEY_AI_PROVIDER             "ai-provider"
#define SETTING_KEY_BUFFERED                "buffered"
#define SETTING_KEY_CONTEXT_FILENAME        "context-filename"
#define SETTING_KEY_DB_HOST                 "db-host"
#define SETTING_KEY_DB_PROVIDER             "db-provider"
#define SETTING_KEY_HELP                    "help"
#define SETTING_KEY_AI_HOST                 "ai-host"
#define SETTING_KEY_AI_MODEL                "ai-model"
#define SETTING_KEY_PROMPT                  "prompt"
#define SETTING_KEY_SYSTEM_PROMPT           "system-prompt"
#define SETTING_KEY_SYSTEM_PROMPT_PROMPT    "prompt"
#define SETTING_KEY_SYSTEM_PROMPT_EXIT      "exit"

#endif // _SETTING_H